#!/bin/bash

set -e
export HOME=/dokku
hash -r
cd $HOME

# Generate supervisord.conf:
bash /build/procfile-to-supervisord /dokku/Procfile /SCALE > supervisord.conf

# Create /var/log/app directory
mkdir -p /var/log/dokku

# Display the generated supervisord.conf:
echo "Generated supervisord.conf:"
cat -n supervisord.conf

# Start up the app:
supervisord -c supervisord.conf
